from enum import Enum


class RetrieveDataType(Enum):
    TRAIN_ORIGINAL = "TRAIN_ORIGINAL"
    TEST_ORIGINAL = "TEST_ORIGINAL"
    TRAIN_NOISE = "TRAIN_NOISE"
    TEST_NOISE = "TEST_NOISE"
    TRAIN_NOISE_ROTATED = "TRAIN_NOISE_ROTATED"
    TEST_NOISE_ROTATED = "TEST_NOISE_ROTATED"
